package com.spot.spotserver.common.domain;

public enum City {
    // 특별,광역시
    SEOUL, BUSAN, GWANGJU_GWANGYEOKSI, DAEJEON, DAEGU, SAEJOENG, ULSAN, INCHEON,

    // GYEONGGI
    SUWON, SEONGNAM, UIJEONGBU, ANYANG, BUCHEON, GWANGMYEONG,
    PYEONGTAEK, ANSAN, GOYANG, GWACHEON, GURI, NAMYANGJU,
    OSAN, SIHEUNG, GUNPO, UIWANG, HANAM, YONGIN, PAJU,
    ICHEON, ANSEONG, GIMPO, HWASEONG, GWANGJU, YANGJU,
    POCHEON, YEOJU, DONGDUCHEON, YEONCHEON, GAPYEONG, YANGPYEONG,

    // GANGWON
    CHUNCHEON, WONJU, GANGNEUNG, DONGHAE, TAEBAEK, SOKCHO, SAMCHEOK,
    HONGCHEON, HOENGSEONG, YEONGWOL, PYEONGCHANG, JEONGSEON, CHEOLWON,
    HWACHEON, YANGGU, INJE, GANGWON_GOSEONG, YANGYANG,

    // GYEONGBUK
    POHANG, GYEONGJU, GIMCHEON, ANDONG, GUMI, YEONGJU,
    YEONGCHEON, SANGJU, MUNGYEONG, GYEONGSAN, GUNWI, UISEONG,
    CHEONGSONG, YEONGYANG, YEONGDEOK, CHEONGDO, GORYEONG,
    SEONGJU, CHILGOK, YECHEON, BONGHWA, ULJIN, ULLEUNG,

    // GYEONGNAM
    CHANGWON, JINJU, TONGYEONG, SACHEON, GIMHAE, MIRYANG,
    GEOJE, YANGSAN, UIRYEONG, HAMAN, CHANGNYEONG, GYEONGNAM_GOSEONG,
    NAMHAE, HADONG, SANCHEONG, HAMYANG, GEOCHANG, HAPCHEON,

    // JEJU
    JEJU, SEOGWIPO,

    // CHUNGBUK
    CHEONGJU, CHUNGJU, JECHEON, BOEUN, OKCHEON, YEONGDONG,
    JEUNGPYEONG, JINCHEON, GOESAN, EUMSEONG, DANYANG,

    // CHUNGNAM
    CHEONAN, GONGJU, BORYEONG, ASAN, SEOSAN, NONSAN,
    GYEORYONG, DANGJIN, GUMSAN, BUYEO, SEOCHEON,
    CHEONGYANG, HONGSEONG, YESAN, TAEAN,    

    // JEONBUK
    JEONJU, GUNSAN, IKSAN, JEONGEUP, NAMWON, GIMJE,
    WANJU, JINAN, MUJU, JANGSU, IMSIL, SUNCHANG,
    GOCHANG, BUAN,

    // JEONNAM
    MOKPO, YEOSU, SUNCHEON, NAJU, GWANGYANG, DAMYANG,
    GOKSEONG, GURYE, GOHEUNG, BOSEONG, HWASUN,
    JANGHEUNG, GANGJIN, HAENAM, YEONGAM, MUAN,
    HAMPYEONG, YEONGGWANG, JANGSEONG, WANDO,
    JINDO, SINAN;
}
